name: Build NEON CITY
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup env
        run: |
          echo "PS3DEV=${{ github.workspace }}/ps3dev" >> $GITHUB_ENV
          echo "PSL1GHT=${{ github.workspace }}/ps3dev" >> $GITHUB_ENV
          sudo apt-get update
          sudo apt-get install -y python2.7 libelf-dev libtool-bin

      - name: Download toolchain
        run: |
          curl -sL https://github.com/bucanero/ps3toolchain/releases/download/ubuntu-latest-fad3b5fb/ps3dev-ubuntu-latest-2020-08-31.tar.gz | tar xz -C ./

      - name: Build
        run: make pkg

      - name: Upload PKG
        uses: actions/upload-artifact@v4
        with:
          name: neoncity-pkg
          path: neoncity.pkg
          if-no-files-found: error